version: '3'
services:
  web:
    image: java_springv1
    build: .
    ports:
      - "8911:8911"
    volumes:
       - ./volumes:/volumes
       - ./tessdata:/app/tessdata
    restart: unless-stopped
